### ISSUE TITLE
 Imminent transfer of this repository within github

### ISSUE THREAD

**Issue by sxa555** [ibmruntimes/v8ppc#126]
This repository was originally set up by Andrew Low to house a fork of V8 and Node.js with additional changes to build and run on IBM platforms. Eventually this became an official IBM project to maintain ports of Node.js to IBM platforms (https://developer.ibm.com/node/sdk/). Andrew has not been working full time on these ports for over a year but the rest of the team has continued to use this repository.

We are planning to move this repository under https://github.com/ibmruntimes/v8ppc following the process documented at https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization. We expect requests to the old repository should automatically be redirected to the new repository after the move. This should be transparent.

We expect this to be done in approximately a week's time from the raising of this issue, but I will provide a more precise update closer to the time.

**Comment by andrewlow** [comment]
It's true - I've been working on other stuff but am proud of the team (and community) that have carried this work forward.

**Comment by sxa555** [comment]
Thanks @andrewlow for all your work kicking off the project - it's been a great success. The current plan is to move the repositories on Monday.

**Comment by sxa555** [comment]
Transfer completed
